name: Awesome readme lint
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  build:
    name: awesome readme lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Scrum/awesome-lint-action@v0.1.0
        with:
          entry: 'README.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}